//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public long Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public string Observaciones { get; set; }
        public decimal Total { get; set; }
        public string CedulaCliente { get; set; }
        public string CedulaUsuario { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
